export const SEARCH_BAR_NO_SEARCH = 'SEARCH_BAR_NO_SEARCH'
export const SEARCH_BAR_SET_STATE = 'SEARCH_BAR_SET_STATE'

export const ACTION_TYPE_SET_TYPE = 'ACTION_TYPE_SET_TYPE'

export const DELETE_COURSE = 'DELETE_COURSE'
export const OPEN_EDIT_COURSE_PAGE = 'OPEN_EDIT_COURSE_PAGE'

export const INPUT_UPDATE_COURSE_INFO = 'INPUT_UPDATE_COURSE_INFO'
export const CHECK_IS_FORM_VALID = 'CHECK_IS_FORM_VALID'

export const SUBMIT_ADD_COURSE = 'SUBMIT_ADD_COURSE'
export const SUBMIT_EDIT_COURSE = 'SUBMIT_EDIT_COURSE'